create database if not exists esis;
create database if not exists na;
create database if not exists local;

create table esis_claims(
BATCH_ID INTEGER PRIMARY KEY,
BATCH_STATUS INTEGER,
RECORD_COUNT INTEGER,
SUCCESS_COUNT INTEGER,
FAILED_COUNT INTEGER,
DUPLICATE_COUNT INTEGER,
RECEIVED_DATE TIMESTAMP,
FILENET_GUID VARCHAR(50)
);

create table claim_connect(
BATCH_ID INTEGER PRIMARY KEY,
BATCH_STATUS INTEGER,
RECORD_COUNT INTEGER,
SUCCESS_COUNT INTEGER,
FAILED_COUNT INTEGER,
DUPLICATE_COUNT INTEGER,
RECEIVED_DATE TIMESTAMP,
FILENET_GUID VARCHAR(50)
);

create table GF_ACE_SUBMISSION_QUOTE(
GF_ACE_SUBMISSION_QUOTE_ID INTEGER PRIMARY KEY,
APP_DB_STATUS_CODE VARCHAR(1),
APP_DB_RETRY_COUNT INTEGER,
FN_STATUS_CODE VARCHAR(1),
FN_RETRY_COUNT INTEGER,
DATE_ADDED TIMESTAMP
);

create table GF_ACE_RT_POLICY(
GF_ACE_POLICY_ID INTEGER PRIMARY KEY,
APP_DB_STATUS_CODE VARCHAR(1),
APP_DB_RETRY_COUNT INTEGER,
FN_STATUS_CODE VARCHAR(1),
FN_RETRY_COUNT INTEGER,
DATE_ADDED TIMESTAMP
);

create table BWH_CLAIMS_ACCOUNT(
GF_ACCOUNT_ID INTEGER PRIMARY KEY,
APP_DB_STATUS_CODE VARCHAR(1),
APP_DB_RETRY_COUNT INTEGER,
FN_STATUS_CODE VARCHAR(1),
FN_RETRY_COUNT INTEGER,
DATE_ADDED TIMESTAMP
);

create table time_keeper(
SOURCE_SYSTEM varchar(50) primary key,
NEXT_RUN_START_TIME timestamp
);